server.port     : ":8000"
server.api_key  : "kmzway87aa"
# Choose a database : mysql || postgres
server.database : "mysql"

mysql.host      : "127.0.0.1"
mysql.port      : "3306"
mysql.database  : "gin-gorm"
mysql.username  : "root"
mysql.password  : "lockedimbar"

psql.host       : "127.0.0.1"
psql.port       : "5432"
psql.database   : "gin-gorm"
psql.username   : "postgres"
psql.password   : "lockedimbar"
psql.sslmode    : "disable"
